# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/grid_editor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(665, 401)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalGroupBox_3 = QtGui.QGroupBox(self.tab)
        self.verticalGroupBox_3.setObjectName(_fromUtf8("verticalGroupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label = QtGui.QLabel(self.verticalGroupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_31.addWidget(self.label)
        self.lineEdit_5 = QtGui.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_31.addWidget(self.lineEdit_5)
        self.label_19 = QtGui.QLabel(self.verticalGroupBox_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_31.addWidget(self.label_19)
        self.comboBox_3 = QtGui.QComboBox(self.verticalGroupBox_3)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_31.addWidget(self.comboBox_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_18 = QtGui.QLabel(self.verticalGroupBox_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_30.addWidget(self.label_18)
        self.lineEdit_6 = QtGui.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_30.addWidget(self.lineEdit_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_30)
        self.verticalLayout_6.addWidget(self.verticalGroupBox_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalGroupBox = QtGui.QGroupBox(self.tab)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.horizontalGroupBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.horizontalGroupBox)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_3.addWidget(self.spinBox_2, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 1, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.horizontalGroupBox)
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_3.addWidget(self.spinBox_3, 2, 2, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.horizontalGroupBox)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_3.addWidget(self.spinBox, 0, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.horizontalGroupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_3)
        self.horizontalLayout_4.addWidget(self.horizontalGroupBox)
        self.horizontalGroupBox1 = QtGui.QGroupBox(self.tab)
        self.horizontalGroupBox1.setObjectName(_fromUtf8("horizontalGroupBox1"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.horizontalGroupBox1)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.checkBox_3 = QtGui.QCheckBox(self.horizontalGroupBox1)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout.addWidget(self.checkBox_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBox_8 = QtGui.QSpinBox(self.horizontalGroupBox1)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout.addWidget(self.spinBox_8, 1, 2, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.horizontalGroupBox1)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout.addWidget(self.spinBox_7, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.horizontalGroupBox1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.horizontalGroupBox1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 1, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout)
        self.horizontalLayout_4.addWidget(self.horizontalGroupBox1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_6.addWidget(self.pushButton)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalGroupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.verticalGroupBox_4.setObjectName(_fromUtf8("verticalGroupBox_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.verticalGroupBox_4)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_2 = QtGui.QLabel(self.verticalGroupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_32.addWidget(self.label_2)
        self.lineEdit_7 = QtGui.QLineEdit(self.verticalGroupBox_4)
        self.lineEdit_7.setText(_fromUtf8(""))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_32.addWidget(self.lineEdit_7)
        self.label_21 = QtGui.QLabel(self.verticalGroupBox_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_32.addWidget(self.label_21)
        self.comboBox_4 = QtGui.QComboBox(self.verticalGroupBox_4)
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.horizontalLayout_32.addWidget(self.comboBox_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_22 = QtGui.QLabel(self.verticalGroupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_33.addWidget(self.label_22)
        self.lineEdit_8 = QtGui.QLineEdit(self.verticalGroupBox_4)
        self.lineEdit_8.setText(_fromUtf8(""))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_33.addWidget(self.lineEdit_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_33)
        self.verticalLayout_11.addWidget(self.verticalGroupBox_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalGroupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.horizontalGroupBox_2.setObjectName(_fromUtf8("horizontalGroupBox_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.horizontalGroupBox_2)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_7 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.horizontalGroupBox_2)
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_4.addWidget(self.spinBox_4, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 1, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.horizontalGroupBox_2)
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_4.addWidget(self.spinBox_5, 2, 2, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.horizontalGroupBox_2)
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_4.addWidget(self.spinBox_6, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.horizontalGroupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 2, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 3, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_4)
        self.horizontalLayout_5.addWidget(self.horizontalGroupBox_2)
        self.horizontalGroupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.horizontalGroupBox_3.setObjectName(_fromUtf8("horizontalGroupBox_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.horizontalGroupBox_3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.checkBox_4 = QtGui.QCheckBox(self.horizontalGroupBox_3)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.spinBox_9 = QtGui.QSpinBox(self.horizontalGroupBox_3)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.gridLayout_2.addWidget(self.spinBox_9, 1, 2, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.horizontalGroupBox_3)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_2.addWidget(self.spinBox_10, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.horizontalGroupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 0, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.horizontalGroupBox_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 1, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 0, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_2)
        self.horizontalLayout_5.addWidget(self.horizontalGroupBox_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_11.addWidget(self.pushButton_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_new_connection = QtGui.QAction(MainWindow)
        self.actionAdd_new_connection.setObjectName(_fromUtf8("actionAdd_new_connection"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("code/gridsync/images/gridsync.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionGitHub_Issues = QtGui.QAction(MainWindow)
        self.actionGitHub_Issues.setObjectName(_fromUtf8("actionGitHub_Issues"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_Gridsync = QtGui.QAction(MainWindow)
        self.actionAbout_Gridsync.setObjectName(_fromUtf8("actionAbout_Gridsync"))
        self.actionShare = QtGui.QAction(MainWindow)
        self.actionShare.setObjectName(_fromUtf8("actionShare"))
        self.actionQuit_2 = QtGui.QAction(MainWindow)
        self.actionQuit_2.setObjectName(_fromUtf8("actionQuit_2"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuFile.addAction(self.actionAdd_new_connection)
        self.menuFile.addAction(self.actionShare)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit_2)
        self.menuHelp.addAction(self.actionGitHub_Issues)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Gridsync)
        self.menu_Edit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_5, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.spinBox_3)
        MainWindow.setTabOrder(self.spinBox_3, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.spinBox_7)
        MainWindow.setTabOrder(self.spinBox_7, self.spinBox_8)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.verticalGroupBox_3.setTitle(_translate("MainWindow", "Connection settings", None))
        self.label.setText(_translate("MainWindow", "Nickname:", None))
        self.lineEdit_5.setText(_translate("MainWindow", "Anonymous", None))
        self.label_19.setText(_translate("MainWindow", "Connection mode:", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Clearnet", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Tor", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "I2P", None))
        self.label_18.setText(_translate("MainWindow", "Introducer:", None))
        self.lineEdit_6.setText(_translate("MainWindow", "pb://hckqqn4vq5ggzuukfztpuu4wykwefa6d@publictestgrid.twilightparadox.com:50213,publictestgrid.lukas-pirl.de:50213,publictestgrid.e271.net:50213,198.186.193.74:50213,68.34.102.231:50213/introducer", None))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "Storage parameters", None))
        self.label_5.setText(_translate("MainWindow", "Total shares (N):", None))
        self.label_6.setText(_translate("MainWindow", "Needed shares (K):", None))
        self.label_13.setText(_translate("MainWindow", "Servers of happiness (H):", None))
        self.horizontalGroupBox1.setTitle(_translate("MainWindow", "Drive sharing", None))
        self.checkBox_3.setText(_translate("MainWindow", "Share this computer\'s free space", None))
        self.label_14.setText(_translate("MainWindow", "Size limit (GB)", None))
        self.label_15.setText(_translate("MainWindow", "Time limit (days):", None))
        self.pushButton.setStatusTip(_translate("MainWindow", "Save settings and reload.", None))
        self.pushButton.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Public Test Grid", None))
        self.verticalGroupBox_4.setTitle(_translate("MainWindow", "Connection settings", None))
        self.label_2.setText(_translate("MainWindow", "Nickname:", None))
        self.label_21.setText(_translate("MainWindow", "Connection mode:", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Clearnet", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Tor", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "I2P", None))
        self.label_22.setText(_translate("MainWindow", "Introducer:", None))
        self.horizontalGroupBox_2.setTitle(_translate("MainWindow", "Storage parameters", None))
        self.label_7.setText(_translate("MainWindow", "Total shares (N):", None))
        self.label_8.setText(_translate("MainWindow", "Needed shares (K):", None))
        self.label_16.setText(_translate("MainWindow", "Servers of happiness (H):", None))
        self.horizontalGroupBox_3.setTitle(_translate("MainWindow", "Drive sharing", None))
        self.checkBox_4.setText(_translate("MainWindow", "Share this computer\'s free space", None))
        self.label_17.setText(_translate("MainWindow", "Size limit (GB)", None))
        self.label_20.setText(_translate("MainWindow", "Time limit (days):", None))
        self.pushButton_2.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "+", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.actionAdd_new_connection.setText(_translate("MainWindow", "Add new connection...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionGitHub_Issues.setText(_translate("MainWindow", "Online documentation...", None))
        self.actionAbout.setText(_translate("MainWindow", "GitHub issues...", None))
        self.actionAbout_Gridsync.setText(_translate("MainWindow", "About Gridsync", None))
        self.actionShare.setText(_translate("MainWindow", "Share this connection...", None))
        self.actionQuit_2.setText(_translate("MainWindow", "Quit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences...", None))

