#!/usr/bin/env python

"""
Checkout a pinned github repository.


Pass this path to a JSON file and a directory to create a checkout in.
This is designed to consume a JSON file managed by 'update-github-repo'.
"""

import argparse
import json
import subprocess
from pathlib import Path

REPO_TEMPLATE = "https://github.com/{owner}/{repo}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "repo_file",
        metavar="repo-file",
        type=Path,
        help="JSON file with pinned configuration.",
    )
    parser.add_argument(
        "checkout_path",
        metavar="checkout-path",
        type=Path,
        help="Path to checkout repository to.",
    )
    args = parser.parse_args()

    repo_file = args.repo_file
    checkout_path = args.checkout_path
    config = json.loads(repo_file.read_text())

    repo_url = REPO_TEMPLATE.format(**config)
    subprocess.run(["git", "clone", repo_url, checkout_path], check=True)
    subprocess.run(
        [
            "git",
            # Done warn about checking out a specific commit
            "-c",
            "advice.detachedHead=false",
            "checkout",
            config["rev"],
        ],
        cwd=checkout_path,
        check=True,
    )


if __name__ == "__main__":
    main()
